### ISSUE TITLE
Setting up SASS, or Material UI/ Bootstrap in the frontend code 

### ISSUE THREAD

**Issue by nikitasharma2692** [UdacityMobileWebScholarship/showcase-app#14]
Hi All, Meanwhile wireframes are getting ready , we can integrate SASS, or Material UI/ Bootstrap in  our code. Provide feedback. I can start on this once stack is finalised.

**Comment by nikitasharma2692** [comment]
Arent we ready with react and from the design it is clear that we have to use material so why not to integrate. We must be ready with skeleton once we have the designs ready.

**Comment by anurag-majumdar** [comment]
I have a suggestion regarding material design part. We can go ahead with the latest version of **material-ui** or we can choose **materialize css** too. As of the latest build, materialize uses vanilla JavaScript instead of jQuery, so it won't create problems regarding performance. There is also another library named Material web components for the web and it is designed officially by devs at Google.

1. Link to Google's official material design: https://material.io/components/web/
2. Link to materialize: http://materializecss.com/
3. Link to material-ui: https://material-ui-next.com/

Both 1st and 2nd frameworks can be easily integrated with any type of front-end code base. I have used both for vanilla projects as well as Angular and React before. Only material-ui is React specific.

**Comment by nikitasharma2692** [comment]
using 3rd option is better , we we will able to directly use components in the react way,  in non react way we have to make individual component for button, input etc... . Best example is popup's or overlays we will not have to worry lifecycle methods just import and apply.

**Comment by anurag-majumdar** [comment]
@nikitasharma2692 yes, that definitely is a part as it is the react way. Other choices can be explored too. For example, the components having JavaScript in them may need to be initialized under a specific lifecycle method like in Angular ngOnInit helps to do so for every JavaScript component's initialization. So in React it will be like overlay.init() for ComponentWillMount lifecycle method in React.

I have personally used all of them and materialize and material design for web components are exactly similar in terms of working too with the above concept in place.

**Comment by highskillzz** [comment]
I think its best we use a react specific ui because not everyone has used react before and are learning now so it would be best if we used something that was tailered for react is my view

**Comment by anurag-majumdar** [comment]
Just in case if another framework is used in place of material-ui we can document it in the style guide section on how to use a JavaScript specific part in code. Generally, tabs, sidenav, parallax and other components which cause interaction are subject to JavaScript code.

**Comment by parmeet1402** [comment]
@nikitasharma2692 
are we done setting up SASS and Material UI? Or i could do that?

**Comment by anurag-majumdar** [comment]
Great to know, can I help setup the material-ui@next for the project by initiating a pull request?

**Comment by blenderskool** [comment]
Good to know that we will be using Material UI.
@anurag-majumdar We would be customizing the styles to match the designs right?

**Comment by anurag-majumdar** [comment]
@blenderskool Yes bro, we can do that. For example the **border-radius** attribute in css wil be quite heavily used I guess. Even I feel the **box-shadow** will be quite heavily used too.

@nikitasharma2692 Alright. Can we start working on a page for the front-end part? Or a new issue needs to be created for it?

**Comment by nikitasharma2692** [comment]
@anurag-majumdar Create a new issue for the same, Will share the PR for the current issue by EOD.

**Comment by blenderskool** [comment]
@nikitasharma2692 Great.
@anurag-majumdar I think we should put all the designs in one place outside the repo. Do you know any place where we can do that? Apparently, with Invision you can't do it without a paid plan. :slightly_smiling_face:

**Comment by blenderskool** [comment]
@anurag-majumdar Ok, I will add them there :slightly_smiling_face:

**Comment by anurag-majumdar** [comment]
@blenderskool I will also add PRs to the desktop folder and will add the finished jpg images there. 😃 . I am working on finishing the designs. After finishing it will do so.

**Comment by ritikrishu** [comment]
I think @divyamrastogi have already invited the designers to Zeplin app.
Is it possible with Zeplin to make a project view only for anyone with the link? If so, the link to designs in readme will suffice. Because most of us won't be able to get dimensions and other stuff from _pngs_. At least I don't know how to use them! 😛

**Comment by blenderskool** [comment]
@ritikrishu I have discussed about Zeplin with @divyamrastogi . I can't use it since it does not work with Linux and the designer that I use. Hence, we have put in there.
@anurag-majumdar I think @ritikrishu is sort of right. We would need dimensions of every component in the design. I would create a detailed style guide that includes all these information and add it there. This would provide us with less burden during development :slightly_smiling_face:

**Comment by blenderskool** [comment]
@ritikrishu @anurag-majumdar I have added guidelines for the basic components of the app. Again, these guidelines may be tweaked a little while development :slightly_smiling_face:

**Comment by anurag-majumdar** [comment]
@blenderskool Yes I agree. Good idea, I will be adding some guidelines which I have in mind as well.
