### ISSUE TITLE
Backend code 

### ISSUE THREAD

**Issue by highskillzz** [UdacityMobileWebScholarship/showcase-app#7]
I just wanted to clarify the backend will be in node right? If so then some people are in a small confusion whether we will be using sails or express as sails is more developed. 

Can the moderators please address this issue?

**Comment by ritikrishu** [comment]
we've a pull request up for client module and general project docs #8 
Although this does not contains general documentation for server module but we'll have the content soon!

**Comment by anurag-majumdar** [comment]
While looking at the thought process for the application, I saw login and register modules too. It looks like we have to include local login. If social login with Google and Facebook is required that can be added too. I have a set of flows I would like to share regarding authentication.

Also, since there is an admin panel and a user panel, so we need a collection schema where the admin and user role is stored along with their salted hash passwords. Let me know what you guys think? We can open a separate issue regarding login if you guys want?

I am also working on the wireframe of the UI side by side.

**Comment by anurag-majumdar** [comment]
@nikitasharma2692 Absolutely. I think this should be addressed asap. Opening an issue for the same.

**Comment by highskillzz** [comment]
admin login and the other social logins can be implemented easily but what about the other ends of the backend

how shall we make the frontend for the project card look like? Also when the user click see more what should we show the user more about the project?
What I am thinking is
The owner can throw in their github project link and its working link and its description and then we can show it in the frontend. What are your thoughts?

**Comment by abhaychawla** [comment]
How can I start contributing to the backend?

**Comment by realslimshanky** [comment]
Closing this issue since we have decided to user Firebase now.
Similar discussion: https://github.com/UdacityMobileWebScholarship/showcase-app/issues/17#issuecomment-383792377
